import Head from 'next/head'
import Image from 'next/image'
import Restart from '../components/Restart';
import Card from '../components/Card'
import styles from '../styles/Home.module.scss'
import {storyPages} from './pages';
import {useState} from 'react'
import { SERVER_PROPS_ID } from 'next/dist/shared/lib/constants'

export default function Home() {
  const [currentPage, setCurrentPage] = useState(1);
  const pages = storyPages;
  const handlePages = (direction) => {
    if (direction === 'Up') {
      currentPage < Object.keys(pages).length ? setCurrentPage(currentPage+1) : null;
    } else {
      currentPage > 1 ? setCurrentPage(currentPage-1) : null;
    }
  }

  const handleChoice = (choiceNumber) => {
    if ((Object.keys(pages).indexOf(choiceNumber) !== -1) || (choiceNumber === 1) || (choiceNumber === 2)) {
      setCurrentPage(choiceNumber);
    } else {
      setCurrentPage("final")
    }
  }

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Sonic{"'"}s Adventure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <em>Sonic{"'"}s Adventure</em>
        </h1>
        <Card prompt={pages[currentPage].prompt || "What does Sonic do next?"} choices={pages[currentPage].choices} description={pages[currentPage].text} img={pages[currentPage].image} handleChoice={handleChoice}/>
        <Restart handleChoice={handleChoice} />
      </main>
    </div>
  )
}
