import sonicBed from '../public/SonicBed.jpg'
import alarmClock from '../public/AlarmClock.jpg'
import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card'
import styles from '../styles/Home.module.css'
import {useState} from 'react'

export default function Home() {
  const [currentImage, setCurrentImage] = useState(1);
  const images = {
    1: sonicBed,
    2: alarmClock
  };
  const text = {
    1: {text:"Sonic sleeps", choices: false},
    2: {text: "Sonic gets up", choices: [
      "Sonic gets mad", "Sonic smiles"
    ]}
  }
  const handlePages = (direction) => {
    if (direction === 'Up') {
      currentImage < Object.keys(images).length ? setCurrentImage(currentImage+1) : null;
    } else {
      currentImage > 1 ? setCurrentImage(currentImage-1) : null;
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Sonic's Adventure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Sonic's Adventure
        </h1>
        <Card choices={text[currentImage].choices} description={text[currentImage].text} img={images[currentImage]}/>
        <div className={styles.nextPage} onClick={()=>handlePages('Down')}>{"<"}</div>
        <div className={styles.nextPage} onClick={()=>handlePages('Up')}>{">"}</div>
      </main>
    </div>
  )
}
